<?php
/**********************************************************************************
* This file is part of package DocuSign By Urdhva Tech.
* Developed by : Urdhva Tech (http://www.urdhva-tech.com)
* Module : DocuSign
* Contact : contact@urdhva-tech.com
* All rights(c) by Urdhva Tech
* This package is licensed software and may only be used in alignment
* with the License Agreement received with this Package.
* This Software is copyrighted and may not be further distributed without
* written consent of Urdhva Tech
*********************************************************************************/
$dictionary['UT_DocuSign'] = array(
    'table'=>'ut_docusign',
    'audited'=>true,
    'inline_edit'=>true,
        'fields'=>array(
  'number' =>
    array(
        'required' => true,
        'name' => 'number',
        'vname' => 'LBL_RS_NUMBER',
        'type' => 'int',
        'len' => 11,
        'isnull' => 'false',
        'unified_search' => true,
        'comments' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'reportable' => true,
        'disable_num_format' => true,
    ),
  'parent_name' =>
  array(
    'required' => false,
    'source' => 'non-db',
    'name' => 'parent_name',
    'vname' => 'LBL_FLEX_RELATE',
    'type' => 'parent',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 25,
    'size' => '20',
    'options' => 'ut_ds_parent_type_display',
    'studio' => 'visible',
    'type_name' => 'parent_type',
    'id_name' => 'parent_id',
    'parent_type' => 'record_type_display',
  ),
  'parent_type' =>
  array(
    'required' => false,
    'name' => 'parent_type',
    'vname' => 'LBL_PARENT_TYPE',
    'type' => 'parent_type',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 255,
    'size' => '20',
    'dbType' => 'varchar',
    'studio' => 'hidden',
  ),
  'parent_id' =>
  array(
    'required' => false,
    'name' => 'parent_id',
    'vname' => 'LBL_PARENT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'email_address' =>
  array(
    'required' => false,
    'name' => 'email_address',
    'vname' => 'LBL_EMAIL_ADDRESS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '150',
    'size' => '20',
  ),
  'docusign_templates' =>
  array(
    'required' => false,
    'name' => 'docusign_templates',
    'vname' => 'LBL_RIGHTSIGNATURE_TEMPLATES',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'docusign_templates_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'sending_type' =>
  array(
    'required' => true,
    'name' => 'sending_type',
    'vname' => 'LBL_SENDING_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'sending_type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'recipient_name' =>
  array(
    'required' => false,
    'name' => 'recipient_name',
    'vname' => 'LBL_RECIPIENT_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '150',
    'size' => '20',
  ),
  'rs_doc_id' =>
  array(
    'required' => false,
    'name' => 'rs_doc_id',
    'vname' => 'LBL_RS_DOC_ID',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'sending_request_id' =>
  array(
    'required' => false,
    'name' => 'sending_request_id',
    'vname' => 'LBL_RS_SENDING_REQ_ID',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'subject' =>
  array(
    'required' => false,
    'name' => 'subject',
    'vname' => 'LBL_SUBJECT',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'message' =>
  array(
    'required' => false,
    'name' => 'message',
    'vname' => 'LBL_MESSAGE',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'state' =>
  array(
    'required' => false,
    'name' => 'state',
    'vname' => 'LBL_STATE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'ds_state_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'rs_created_at' =>
  array(
    'required' => false,
    'name' => 'rs_created_at',
    'vname' => 'LBL_RS_CREATED_AT',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
  ),
  'rs_completed_at' =>
  array(
    'required' => false,
    'name' => 'rs_completed_at',
    'vname' => 'LBL_RS_COMPLETED_AT',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
  ),
  'rs_expires_on' =>
  array(
    'required' => false,
    'name' => 'rs_expires_on',
    'vname' => 'LBL_RS_EXPIRES_ON',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
  ),
  'rs_declined_on' =>
  array(
    'required' => false,
    'name' => 'rs_declined_on',
    'vname' => 'LBL_RS_DECLINED_ON',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
  ),
  'rs_voided_on' =>
  array(
    'required' => false,
    'name' => 'rs_voided_on',
    'vname' => 'LBL_RS_VOIDED_ON',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
  ),
  
  'saved_template_roles' =>
  array(
    'required' => false,
    'name' => 'saved_template_roles',
    'vname' => 'LBL_SAVED_TEMPLATE_ROLES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'download_ds_notes' =>
  array(
    'required' => false,
    'name' => 'download_ds_notes',
    'vname' => 'LBL_DOWNLOAD_DS_NOTES',
    'type' => 'varchar',
    'source'=>'non-db',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'sending_option' =>
  array(
    'required' => true,
    'name' => 'sending_option',
    'vname' => 'LBL_SENDING_OPTION',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'email',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 25,
    'size' => '20',
    'options' => 'ds_sending_option_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'ut_docusign_ut_dsactivities' =>
      array(
          'name' => 'ut_docusign_ut_dsactivities',
          'type' => 'link',
          'relationship' => 'ut_docusign_ut_dsactivities',
          'source' => 'non-db',
          'module' => 'UT_DSActivities',
          'bean_name' => false,
          'side' => 'right',
          'vname' => 'LBL_UT_DOCUSIGN_UT_RSACTIVITIES_FROM_UT_RSACTIVITIES_TITLE',
      ),
  'ut_dssigners_ut_docusign' =>
      array(
          'name' => 'ut_dssigners_ut_docusign',
          'type' => 'link',
          'relationship' => 'ut_dssigners_ut_docusign',
          'source' => 'non-db',
          'module' => 'UT_DSSigners',
          'bean_name' => false,
          'side' => 'right',
          'vname' => 'LBL_UT_SIGNERS_UT_DOCUSIGN_FROM_UT_SIGNERS_TITLE',
      ),
  'ut_docusign_accounts_1' =>
  array(
      'name' => 'ut_docusign_accounts_1',
      'type' => 'link',
      'relationship' => 'ut_docusign_accounts_1',
      'source' => 'non-db',
      'module' => 'Accounts',
      'bean_name' => 'Account',
      'vname' => 'LBL_UT_DOCUSIGN_ACCOUNTS_1_FROM_ACCOUNTS_TITLE',
  ),
  'ut_docusign_contacts_1' =>
  array(
      'name' => 'ut_docusign_contacts_1',
      'type' => 'link',
      'relationship' => 'ut_docusign_contacts_1',
      'source' => 'non-db',
      'module' => 'Contacts',
      'bean_name' => 'Contact',
      'vname' => 'LBL_UT_DOCUSIGN_CONTACTS_1_FROM_CONTACTS_TITLE',
  ),
  'ut_docusign_leads_1' =>
  array(
      'name' => 'ut_docusign_leads_1',
      'type' => 'link',
      'relationship' => 'ut_docusign_leads_1',
      'source' => 'non-db',
      'module' => 'Leads',
      'bean_name' => 'Lead',
      'vname' => 'LBL_UT_DOCUSIGN_LEADS_1_FROM_LEADS_TITLE',
  ),
  'ut_docusign_prospects_1' =>
  array(
      'name' => 'ut_docusign_prospects_1',
      'type' => 'link',
      'relationship' => 'ut_docusign_prospects_1',
      'source' => 'non-db',
      'module' => 'Prospects',
      'bean_name' => 'Prospect',
      'vname' => 'LBL_UT_DOCUSIGN_PROSPECTS_1_FROM_PROSPECTS_TITLE',
  ),
  'ut_docusign_aos_contracts_1' =>
  array(
      'name' => 'ut_docusign_aos_contracts_1',
      'type' => 'link',
      'relationship' => 'ut_docusign_aos_contracts_1',
      'source' => 'non-db',
      'module' => 'AOS_Contracts',
      'bean_name' => 'AOS_Contracts',
      'vname' => 'LBL_UT_DOCUSIGN_AOS_CONTRACTS_1_FROM_AOS_CONTRACTS_TITLE',
  ),
  'ut_docusign_aos_quotes_1' =>
  array(
      'name' => 'ut_docusign_aos_quotes_1',
      'type' => 'link',
      'relationship' => 'ut_docusign_aos_quotes_1',
      'source' => 'non-db',
      'module' => 'AOS_Quotes',
      'bean_name' => 'AOS_Quotes',
      'vname' => 'LBL_UT_DOCUSIGN_AOS_QUOTES_1_FROM_AOS_QUOTES_TITLE',
  ),
  'ut_docusign_users_1' =>
  array(
      'name' => 'ut_docusign_users_1',
      'type' => 'link',
      'relationship' => 'ut_docusign_users_1',
      'source' => 'non-db',
      'module' => 'Users',
      'bean_name' => 'User',
      'vname' => 'LBL_UT_DOCUSIGN_USERS_1_FROM_USERS_TITLE',
  ),
  'ut_docusign_notes_1' =>
  array(
      'name' => 'ut_docusign_notes_1',
      'type' => 'link',
      'relationship' => 'ut_docusign_notes_1',
      'source' => 'non-db',
      'module' => 'Notes',
      'bean_name' => 'Note',
      'side' => 'right',
      'vname' => 'LBL_UT_DOCUSIGN_NOTES_1_FROM_NOTES_TITLE',
  ),
  'ut_dsfieldmapping_ut_docusign_1' =>
  array(
      'name' => 'ut_dsfieldmapping_ut_docusign_1',
      'type' => 'link',
      'relationship' => 'ut_dsfieldmapping_ut_docusign_1',
      'source' => 'non-db',
      'module' => 'UT_DSFieldMapping',
      'bean_name' => 'UT_DSFieldMapping',
      'vname' => 'LBL_UT_DSFIELDMAPPING_UT_DOCUSIGN_1_FROM_UT_DSFIELDMAPPING_TITLE',
      'id_name' => 'ut_dsfieldmapping_ut_docusign_1ut_dsfieldmapping_ida',
  ),
  'ut_dsfieldmapping_ut_docusign_1_name' =>
  array(
      'name' => 'ut_dsfieldmapping_ut_docusign_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_UT_DSFIELDMAPPING_UT_DOCUSIGN_1_FROM_UT_DSFIELDMAPPING_TITLE',
      'save' => true,
      'id_name' => 'ut_dsfieldmapping_ut_docusign_1ut_dsfieldmapping_ida',
      'link' => 'ut_dsfieldmapping_ut_docusign_1',
      'table' => 'ut_dsfieldmapping',
      'module' => 'UT_DSFieldMapping',
      'rname' => 'name',
  ),
  'ut_dsfieldmapping_ut_docusign_1ut_dsfieldmapping_ida' =>
  array(
      'name' => 'ut_dsfieldmapping_ut_docusign_1ut_dsfieldmapping_ida',
      'type' => 'link',
      'relationship' => 'ut_dsfieldmapping_ut_docusign_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_UT_DSFIELDMAPPING_UT_DOCUSIGN_1_FROM_UT_DOCUSIGN_TITLE',
  ),
  'ut_dsfieldmapping_ut_docusign_2' =>
  array(
      'name' => 'ut_dsfieldmapping_ut_docusign_2',
      'type' => 'link',
      'relationship' => 'ut_dsfieldmapping_ut_docusign_2',
      'source' => 'non-db',
      'module' => 'UT_DSFieldMapping',
      'bean_name' => 'UT_DSFieldMapping',
      'vname' => 'LBL_UT_DSFIELDMAPPING_UT_DOCUSIGN_2_FROM_UT_DSFIELDMAPPING_TITLE',
      'id_name' => 'ut_dsfieldmapping_ut_docusign_2ut_dsfieldmapping_ida',
    ),
  'ut_dsfieldmapping_ut_docusign_2_name' =>
  array(
      'name' => 'ut_dsfieldmapping_ut_docusign_2_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_UT_DSFIELDMAPPING_UT_DOCUSIGN_2_FROM_UT_DSFIELDMAPPING_TITLE',
      'save' => true,
      'id_name' => 'ut_dsfieldmapping_ut_docusign_2ut_dsfieldmapping_ida',
      'link' => 'ut_dsfieldmapping_ut_docusign_2',
      'table' => 'ut_dsfieldmapping',
      'module' => 'UT_DSFieldMapping',
      'rname' => 'name',
  ),
  'ut_dsfieldmapping_ut_docusign_2ut_dsfieldmapping_ida' =>
  array(
      'name' => 'ut_dsfieldmapping_ut_docusign_2ut_dsfieldmapping_ida',
      'type' => 'link',
      'relationship' => 'ut_dsfieldmapping_ut_docusign_2',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_UT_DSFIELDMAPPING_UT_DOCUSIGN_2_FROM_UT_DOCUSIGN_TITLE',
  ),
  /*
  'ut_docusign_documents_1' =>
  array(
      'name' => 'ut_docusign_documents_1',
      'type' => 'link',
      'relationship' => 'ut_docusign_documents_1',
      'source' => 'non-db',
      'module' => 'Documents',
      'bean_name' => 'Document',
      'side' => 'right',
      'vname' => 'LBL_UT_DOCUSIGN_DOCUMENTS_1_FROM_DOCUMENTS_TITLE',
  )
  */
),
    'relationships'=>array(
),
    'optimistic_locking'=>true,
        'unified_search'=>true,
    );
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('UT_DocuSign', 'UT_DocuSign', array('basic','assignable','security_groups','file'));
