<?php
/**********************************************************************************
* This file is part of package DocuSign By Urdhva Tech.
* Developed by : Urdhva Tech (http://www.urdhva-tech.com)
* Module : DocuSign
* Contact : contact@urdhva-tech.com
* All rights(c) by Urdhva Tech
* This package is licensed software and may only be used in alignment
* with the License Agreement received with this Package.
* This Software is copyrighted and may not be further distributed without
* written consent of Urdhva Tech
*********************************************************************************/
$dictionary['UT_DSSigners'] = array(
    'table'=>'ut_dssigners',
    'audited'=>true,
    'inline_edit'=>true,
        'duplicate_merge'=>true,
        'fields'=>array(
  'name' =>
  array(
    'name' => 'name',
    'vname' => 'LBL_NAME',
    'type' => 'name',
    'link' => true,
    'dbType' => 'varchar',
    'len' => '255',
    'unified_search' => false,
    'full_text_search' =>
    array(
      'boost' => 3,
    ),
    'required' => true,
    'importable' => 'required',
    'duplicate_merge' => 'disabled',
    'merge_filter' => 'disabled',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'size' => '20',
  ),
  'recipient_email' =>
  array(
    'required' => true,
    'name' => 'recipient_email',
    'vname' => 'LBL_RECIPIENT_EMAIL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'role' =>
  array(
    'required' => false,
    'name' => 'role',
    'vname' => 'LBL_ROLE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'rs_doc_id' =>
  array(
    'required' => false,
    'name' => 'rs_doc_id',
    'vname' => 'LBL_RS_DOC_ID',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'parent_name' =>
  array(
    'required' => false,
    'source' => 'non-db',
    'name' => 'parent_name',
    'vname' => 'LBL_RELATE_MODULE',
    'type' => 'parent',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 25,
    'size' => '20',
    'options' => 'ut_ds_parent_type_display',
    'studio' => 'visible',
    'type_name' => 'parent_type',
    'id_name' => 'parent_id',
    'parent_type' => 'record_type_display',
  ),
  'parent_type' =>
  array(
    'required' => false,
    'name' => 'parent_type',
    'vname' => 'LBL_PARENT_TYPE',
    'type' => 'parent_type',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 255,
    'size' => '20',
    'dbType' => 'varchar',
    'studio' => 'hidden',
  ),
  'parent_id' =>
  array(
    'required' => false,
    'name' => 'parent_id',
    'vname' => 'LBL_PARENT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
   'ut_dssigners_ut_docusign' =>
  array(
      'name' => 'ut_dssigners_ut_docusign',
      'type' => 'link',
      'relationship' => 'ut_dssigners_ut_docusign',
      'source' => 'non-db',
      'module' => 'UT_DocuSign',
      'bean_name' => 'UT_DocuSign',
      'vname' => 'LBL_UT_SIGNERS_UT_DOCUSIGN_FROM_UT_DOCUSIGN_TITLE',
      'id_name' => 'ut_dssigners_ut_docusignut_docusign_ida',
  ),
   'ut_dssigners_ut_docusign_name' =>
  array(
      'name' => 'ut_dssigners_ut_docusign_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_UT_SIGNERS_UT_DOCUSIGN_FROM_UT_DOCUSIGN_TITLE',
      'save' => true,
      'id_name' => 'ut_dssigners_ut_docusignut_docusign_ida',
      'link' => 'ut_dssigners_ut_docusign',
      'table' => 'ut_docusign',
      'module' => 'UT_DocuSign',
      'rname' => 'document_name',
  ),
   'ut_dssigners_ut_docusignut_docusign_ida' =>
  array(
      'name' => 'ut_dssigners_ut_docusignut_docusign_ida',
      'type' => 'link',
      'relationship' => 'ut_dssigners_ut_docusign',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_UT_SIGNERS_UT_DOCUSIGN_FROM_UT_SIGNERS_TITLE',
  ),
),
    'relationships'=>array(
),
    'optimistic_locking'=>true,
        'unified_search'=>true,
    );
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('UT_DSSigners', 'UT_DSSigners', array('basic','assignable','security_groups'));
