<?php
/**********************************************************************************
* This file is part of package DocuSign By Urdhva Tech.
* Developed by : Urdhva Tech (http://www.urdhva-tech.com)
* Module : DocuSign
* Contact : contact@urdhva-tech.com
* All rights(c) by Urdhva Tech
* This package is licensed software and may only be used in alignment
* with the License Agreement received with this Package.
* This Software is copyrighted and may not be further distributed without
* written consent of Urdhva Tech
*********************************************************************************/
$dictionary['UT_DSFieldMapping'] = array(
    'table' => 'ut_dsfieldmapping',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
  'docusign_templates' =>
  array(
    'required' => false,
    'name' => 'docusign_templates',
    'vname' => 'LBL_DOCUSIGN_TEMPLATES',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'docusign_templates_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'ds_roles' =>
  array(
    'required' => false,
    'name' => 'ds_roles',
    'vname' => 'LBL_DS_ROLES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'crm_modules' =>
  array(
    'required' => false,
    'name' => 'crm_modules',
    'vname' => 'LBL_CRM_MODULES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'field_mapping' =>
  array(
    'required' => false,
    'name' => 'field_mapping',
    'vname' => 'LBL_FIELD_MAPPING',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'synchronizing_direction' =>
  array(
    'required' => true,
    'name' => 'synchronizing_direction',
    'vname' => 'LBL_SYNCHRONIZING_DIRECTION',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'synchronizing_direction_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'crmroledata' =>
  array(
    'required' => false,
    'name' => 'crmroledata',
    'vname' => 'LBL_CRMROLEDATA',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'crmrowdata' =>
  array(
    'required' => false,
    'name' => 'crmrowdata',
    'vname' => 'LBL_CRMROWDATA',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'ut_dsfieldmapping_ut_docusign_1' =>
  array(
      'name' => 'ut_dsfieldmapping_ut_docusign_1',
      'type' => 'link',
      'relationship' => 'ut_dsfieldmapping_ut_docusign_1',
      'source' => 'non-db',
      'module' => 'UT_DocuSign',
      'bean_name' => 'UT_DocuSign',
      'side' => 'right',
      'vname' => 'LBL_UT_DSFIELDMAPPING_UT_DOCUSIGN_1_FROM_UT_DOCUSIGN_TITLE',
  ),
  'ut_dsfieldmapping_ut_docusign_2' =>
  array(
      'name' => 'ut_dsfieldmapping_ut_docusign_2',
      'type' => 'link',
      'relationship' => 'ut_dsfieldmapping_ut_docusign_2',
      'source' => 'non-db',
      'module' => 'UT_DocuSign',
      'bean_name' => 'UT_DocuSign',
      'side' => 'right',
      'vname' => 'LBL_UT_DSFIELDMAPPING_UT_DOCUSIGN_2_FROM_UT_DOCUSIGN_TITLE',
  ),

),
    'relationships' => array(
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('UT_DSFieldMapping', 'UT_DSFieldMapping', array('basic','assignable','security_groups'));
